### ISSUE TITLE
Documentation: BinaryHeap.compare

### ISSUE THREAD

**Issue by hungarian-notation** [zandaqo/structurae#18]
The documentation gives an example alternative compare function for  as:

```javascript
const { BinaryHeap } = require('structurae');

class MaxHeap extends BinaryHeap {}
MaxHeap.compare = (a, b) => b - a; 
```

This example will not compile in a typescript project, as BinaryHeap.compare has the signature:

```typescript
static compare(a: any, b: any): boolean;
```

It appears that the implementation does indeed expect a boolean result from compare, and as such the documentation should probably be something like:

```javascript
const { BinaryHeap } = require('structurae');

class MaxHeap extends BinaryHeap {}
MaxHeap.compare = (a, b) => a > b; 
```

**Comment by zandaqo** [comment]
Yes, indeed `BineryHeap#compare` returns a boolean. Thanks!
